### PR TITLE
Run Envoy as root in Openshift as chown is not allowed

### PR DESCRIPTION
**Pull request by dobrerazvan**
```
kubectl logs -f envoy-secure-secureingress-az2-pipeline-kafka-7c4cc7f497-czjfn
chown: changing ownership of '/dev/stdout': Permission denied
chown: changing ownership of '/dev/stderr': Permission denied
```

### CODE REVIEW

**Review by azun — APPROVED** [review]
Looks good. Do we need a github action for building and pushing to ghcr?

**Comment by dobrerazvan** [comment]
> Looks good. Do we need a github action for building and pushing to ghcr?

Yeah, we might need to add some build pipeline if we are maintaining this fix.

**Comment by dobrerazvan** [comment]
to @azun's suggestion, https://github.com/moby/moby/issues/31243#issuecomment-406879017 looks a better approach that can be proposed upstream as well.

**Review by cristianpetrache — APPROVED** [review]

**Comment by dobrerazvan** [comment]
Closing as https://git.corp.adobe.com/experience-platform/pipeline-kafka/pull/978 implements the fix while using the vanila envoy image.

**Pull request closed without merging**
